config/routes.rb
Rails.application.routes.draw do

#ユーザー
 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#管理者
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

#検索機能
devise_scope :user do
  get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
end

#ホームページ
root to: 'public/homes#top'


get "search" => "searches#search"

namespace :admin do
 resources :customers #管理者
end

namespace :public do
 resources :users do #顧客
   member do
    get :filmfavorites
   end
 end

 resources :movies do #映画情報
  resource :favorites, only: [:create, :destroy]
 end

 resources :films do #映画感想
  resource :filmfavorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
 end

#退会機能
get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
end

end



# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
   @customers = Movie.page(params[:page]).per(15)
   @customers = Film.page(params[:page]).per(15)
   @customers = User.page(params[:page]).per(15)
  end

  def show
    @movies = Movie.page(params[:page]).per(5)
    @films = Film.page(params[:page]).per(5)
    @user = User.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
    @film = Film.find(params[:id])
    @user = User.find(params[:id])

  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to public_user_path
    else
      render edit_public_user_path
    end
  end



  private
  def movie_params
    params.require(:movie).permit(:title, :body)
  end

  def film_params
    params.require(:film).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :email, :image, :is_deleted)
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <%= @user.name %>さんの投稿
  <%= form_with model: @movie, url:  admin_customer_path, method: :patch do |f| %>
    <div class="row">
      <div class="card" style="width: 1000px; height: 150px; border: 2px solid; margin: 10px">
        <%= link_to  @movie.title, edit_admin_customer_path %><br>
        <%= @movie.body %>
      </div>
    </div>
  <% end %>
  
  <%= form_with model: @film, url:  admin_customer_path, method: :patch do |f| %>
      <div class="row">
        <div class="card" style="width: 1000px; height: 150px; border: 2px solid; margin: 10px">
            <%= link_to  @film.title, edit_admin_customer_path %><br>
            <%= @film.body %>
        </div>
      </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<h2>顧客一覧</h2>
 <table class="table table-hover table-bordered table-condensed">
    <thead>
      <tr class="info">
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td class="info col-xs-1">
          <%= customer.id %>
        </td>
        <td class="text-left">
          <%= link_to customer.name,  admin_customer_path(customer.id) %>
        </td>
        <td class="text-left">
          <%= customer.email %>
        </td>
        <td class="text-left">
          <% if customer.is_deleted == true %>
            <strong><i class="text-secondary">退会済</i></strong>
          <% else customer.is_deleted == false %>
            <strong><i class="text-success">有効</i></span></strong>
          <% end %>
        </td>
    <% end %>
     </td>
      </tr>
  </tbody>
</table>

<div class="row">
  <div style= "margin: auto">
    <font size="5"><%= paginate @customers %></font>
  </div>
</div>

app/views/admin/customers/show.html.erb
<% @films.each do |film| %>
  <% film.comments.each do |comment| %>
    <div class="container">
      <div class="row">
        <div class="card" style="width: 1000px; height: 150px; border: 2px solid; margin: 10px">
          <% next if comment.id.blank? %>
          <%= comment.user.name %><br>
          <%= comment.comment %>
           <div class="d-flex align-items-end">
              <div style="margin-left: 900px; margin-bottom: 100px">
                <%= link_to "削除", public_film_comment_path(comment.film,comment), method: :delete, class: "btn btn-sm btn-danger" %>
              </div>
           </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<div class="row">
  <div style= "margin: auto">
    <font size="5"><%= paginate @films %></font>
  </div>
</div>