config/routes.rb
Rails.application.routes.draw do

#ユーザー
 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

#管理者
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

#検索機能
devise_scope :user do
  get 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
end

#ホームページ
root to: 'public/homes#top'


get "search" => "searches#search"

namespace :admin do
 resources :customers #管理者
end

namespace :public do
 resources :users do #顧客
   member do
    get :filmfavorites
   end
 end

 resources :movies do #映画情報
  resource :favorites, only: [:create, :destroy]
 end

 resources :films do #映画感想
  resource :filmfavorites, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
 end

#退会機能
get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
end

end



# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :film
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
   belongs_to :user
   belongs_to :movie
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user
  has_many :film_favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  #いいね機能
  def filmfavorited?(user)
   FilmFavorite.where(user_id: user.id, film_id: self.id).exists?
  end

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @film = Film.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @film = Film.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @film = Film.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @film = Film.where("name LIKE?","%#{word}%")
    else
      @film = Film.all
    end
  end
end

app/models/film_favorite.rb
class FilmFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :film
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true

  #いいね機能
  def favorited?(user)
   self.favorites.where(user_id: user.id).exists?
  end

  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @movie = Movie.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @movie = Movie.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @movie = Movie.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @movie = Movie.where("title LIKE?","%#{word}%")
    else
      @movie = Movie.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :films, dependent: :destroy
  has_many :movies, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :film_favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  #ゲストログイン機能
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
   end
  end


  def active_for_authentication?
    super && (is_deleted == false)
  end


  #検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  validates :email, presence: true
  validates :name, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
   @customers = Movie.page(params[:page]).per(15)
   @customers = Film.page(params[:page]).per(15)
   @customers = User.page(params[:page]).per(15)
  end

  def show
    @movies = Movie.page(params[:page]).per(5)
    @films = Film.page(params[:page]).per(5)
    @user = User.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
    @film = Film.find(params[:id])
    @user = User.find(params[:id])

  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to public_user_path
    else
      render edit_public_user_path
    end
  end



  private
  def movie_params
    params.require(:movie).permit(:title, :body)
  end

  def film_params
    params.require(:film).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :email, :image, :is_deleted)
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @movies = Movie.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'guestuserでログインしました。'
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eiga</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-expand-lg navbar-dark bg-dark">
  <h2><%= link_to "commovie", root_path %></h2>
    <% if user_signed_in? %>

    <li class="nav-item m-3">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </li>

    <li class="nav-item m-3">
      <%= link_to "マイページ", public_user_path(current_user) %>
    </li>

    <li class="nav-item m-3">
      <%= link_to "映画情報", public_movies_path %>
    </li>

     <li class="nav-item m-3">
      <%= link_to "映画感想", public_films_path %>
    </li>

    <li class="nav-item m-3">
      <%= link_to "投稿する", public_movie_path(current_user) %>
    </li>

    <li class="nav-item m-3">
      <%= render 'public/homes/serach', movie: @movie %>
    </li>

    <% elsif admin_signed_in? %>
    <li class="nav-item m-3">
      <%= link_to "顧客一覧", admin_customers_path, class: 'btn btn-outline-secondary' %>
    </li>

    <li class="nav-item m-3">
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-secondary' %>
    </li>

    <% else %>
   <li class="nav-item m-3">
      <%= link_to "新規登録", new_user_registration_path, class: 'btn btn-outline-secondary' %>
    </li>

    <li class="nav-item m-3">
      <%= link_to "ログイン", new_user_session_path, class: 'btn btn-outline-secondary' %>
    </li>

    <li class="nav-item m-3">
      <%= link_to 'ゲストログイン', users_guest_sign_in_path, class: 'btn btn-outline-secondary' %>
    </li>
    <% end %>

  </ul>
  </div>
</header>

<%= notice %>
<%= alert %>

 <main>
  <%= yield %>
 </main>



   <footer class="fixed-bottom" style="height:130px; background-color: #f5af7d;">
        <div class="container">
          <div class="row no-gutters">
            <div class="col-md-4">
              <p>映画情報コミュニティサイト</p>
            </div>
            <div class="col-md-8">
              <h6 class="text-white mt-2 mb-3">Link</h6>
              <ul class="p-0 list-unstyled">
                <li>
                  <a href="" title="About" class="text-white-50">会社概要</a>
                </li>
                <li>
                  <a href="" title="License informations" class="text-white-50">プライバシーポリシー</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
    </footer>
  </div>
 </body>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</html>